spring.datasource.url=jdbc:postgresql://localhost:5432/bd_emergencias_nacional
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Reglas de Hibernate: 'none' es CRÍTICO para que no modifique tu tabla consolidada
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true